const form =  [
  {
    "id": "1",
    "t_id": "1",
    "type": "1",
    "trans_key": "期望城市",
    "tbl": "city",
    "tbl_val": "",
    "val_type": "1",
    "val_json": null,
    "field_id": "2",
    "is_required": "2",
    "sort": "10",
    "drop_source": "",
    "name": "期望城市",
    "t_name": "基本信息",
    "val_type_name": "field_val_type.1",
    "children": [],
    'formType': 'FleSelect',
    'col': '24',
    'display': true
  },
  {
    "id": "6",
    "t_id": "1",
    "type": "1",
    "trans_key": "岗位类型",
    "tbl": "resume",
    "tbl_val": "",
    "val_type": "2",
    "val_json": null,
    "field_id": "2",
    "is_required": "2",
    "sort": "10",
    "drop_source": "",
    "name": "岗位类型",
    "t_name": "基本信息",
    "val_type_name": "field_val_type.2",
    "children": [],
    'formType': 'FleSelect',
    'col': '24',
    'display': true
  },
  {
    "id": "7",
    "t_id": "1",
    "type": "1",
    "trans_key": "姓名",
    "tbl": "first_name",
    "tbl_val": "",
    "val_type": "1",
    "val_json": null,
    "field_id": "2",
    "is_required": "2",
    "sort": "10",
    "drop_source": "",
    "name": "姓名",
    "t_name": "基本信息",
    "val_type_name": "field_val_type.1",
    "children": [{
      "id": "7",
      "t_id": "1",
      "type": "1",
      "trans_key": "姓名",
      "tbl": "first_name",
      "tbl_val": "",
      "val_type": "1",
      "val_json": null,
      "field_id": "2",
      "is_required": "2",
      "sort": "10",
      "drop_source": "",
      "name": "姓名",
      "t_name": "基本信息",
      "val_type_name": "field_val_type.1",
      "children": [],
      'formType': 'FleField',
      'col': '8',
      'display': true
      },
      {
        "id": "8",
        "t_id": "1",
        "type": "1",
        "trans_key": "",
        "tbl": "last_name",
        "tbl_val": "",
        "val_type": "1",
        "val_json": null,
        "field_id": "2",
        "is_required": "2",
        "sort": "10",
        "drop_source": "",
        "name": "姓名",
        "t_name": "基本信息",
        "val_type_name": "field_val_type.1",
        "children": [],
        'formType': 'FleField',
        'col': '16',
        'display': true
      }
    ],
    'formType': 'Input',
    'col': '8',
    'display': true
  },
  {
    "id": "3",
    "t_id": "1",
    "type": "1",
    "trans_key": "性别",
    "tbl": "gender",
    "tbl_val": "",
    "val_type": "2",
    "val_json": null,
    "field_id": "5",
    "is_required": "2",
    "sort": "10",
    "drop_source": "\/custmoize\/getFieldValTypeDetailList",
    "name": "性别",
    "t_name": "个人信息",
    "val_type_name": "field_val_type.2",
    "children": [],
    'formType': 'FleField',
    'col': '24',
    'display': true
  }
]

export default form